"""Detection signals.

Milestone 3: Signal 1 only — the Groq LLM classifier.
Signal 2 (stylometry) and the combined confidence scorer arrive in Milestone 4.

Signal 1 contract (planning.md §2.1):
    llm_signal(text) -> {"ai_probability": float in [0,1], "rationale": str}
"""
import json
import os

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a forensic writing analyst assessing whether a piece of text was "
    "written by a human or generated by an AI language model. Judge holistically: "
    "voice, idiosyncrasy, surprise, and topical grounding suggest a human; "
    "relentlessly even, hedged, cliche-leaning, uniformly developed prose suggests "
    "AI. You are not certain, and short texts are hard to judge — reflect that in "
    "your score. Respond ONLY with a JSON object of the form "
    '{"score": <integer 0-100>, "rationale": "<one short sentence>"} '
    "where 0 means certainly human and 100 means certainly AI-generated."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env)")
        _client = Groq(api_key=api_key)
    return _client


def llm_signal(text):
    """Signal 1: ask Groq how AI-like the text reads.

    Returns {"ai_probability": float 0..1, "rationale": str}.
    Raises on API/parse failure so the caller can decide how to degrade.
    """
    resp = _get_client().chat.completions.create(
        model=MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    raw = resp.choices[0].message.content
    data = json.loads(raw)
    score = float(data["score"])
    score = max(0.0, min(100.0, score)) / 100.0
    rationale = str(data.get("rationale", "")).strip()
    return {"ai_probability": score, "rationale": rationale}
